
rng('default') % set the random number generator seed
feat1 = encode(autoenc1,xTrainImages);
hiddenSize2 = 100; % set the number of hidden nodes in Layer 2
autoenc2 = trainAutoencoder(feat1,hiddenSize2, ...
'MaxEpochs',400, ...
'EncoderTransferFunction','satlin',...
'DecoderTransferFunction','purelin',...
'L2WeightRegularization',0.002, ...
'SparsityRegularization',4, ...
'SparsityProportion',0.1, ...
'ScaleData', false);