
rng('default') % set the random number generator seed
feat2 = encode(autoenc2,feat1);
hiddenSize3 = 50; % set the number of hidden nodes in Layer 2
autoenc3 = trainAutoencoder(feat2,hiddenSize3, ...
'MaxEpochs',400, ...
'EncoderTransferFunction','satlin',...
'DecoderTransferFunction','purelin',...
'L2WeightRegularization',0.002, ...
'SparsityRegularization',4, ...
'SparsityProportion',0.1, ...
'ScaleData', false);